version: '3'
services:
    server:
        image: becarios-autentia/expenses-web-app-image
        ports:
            - "4300:80"
        tty: true
        expose:
            - "4300"
        stdin_open: true
        environment:
            - MODE=dev
        networks:
            - my-network
networks:
  my-network:
    external: true
